### ISSUE TITLE
CleanEmbeddedChildrenMixin should propagate rollback

### ISSUE THREAD

**Issue by agebhar1** [lolmaus/ember-cli-stained-by-children#3]
Hi,

currently in case of canceling modification on either the root record or one of its embedded childs (records) by `record.rollback()` does not propagate the call to its dependencies. Hence a modified child will stuck on `child.get('isDirty')` and also its owner/root record even rollback was called on root. For symmetry `CleanEmbeddedChildrenMixin` should also propagate `rollback` next to `save`.

**Comment by lolmaus** [comment]
This is awesome, @agebhar1!

Let me find some time to see your test failing on the current version and passing on the PR version, and i'll merge it.

**Comment by lolmaus** [comment]
Closed in #4 by @agebhar1.
