### ISSUE TITLE
Add `tmp` dir to the .npmignore.

### ISSUE THREAD

**Issue by stefanpenner** [lolmaus/ember-cli-stained-by-children#9]
https://github.com/ember-cli/ember-cli/issues/4199

**Comment by lolmaus** [comment]
Like this?

https://github.com/lolmaus/ember-cli-stained-by-children/blob/0.x/.npmignore#L13

**Comment by stefanpenner** [comment]
like this: https://github.com/ember-cli/ember-cli/blob/master/blueprints/addon/files/npmignore#L3

**Comment by lolmaus** [comment]
Thank you, kind sir.
